<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Majlis.Tasks.EntityFrameworkCore</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Majlis.Tasks.Domain\Majlis.Tasks.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Majlis.Framework.EntityFrameworkCore\Majlis.Framework.EntityFrameworkCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
</Project>
