<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Majlis.Framework.EntityFrameworkCore</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Majlis.Framework.Domain\Majlis.Framework.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" />
  </ItemGroup>
</Project>
