<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Majlis.Workspaces.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Majlis.Workspaces.Domain\Majlis.Workspaces.Domain.csproj" />
    <ProjectReference Include="..\Majlis.Workspaces.EntityFrameworkCore\Majlis.Workspaces.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\Shared\Majlis.Framework.Application\Majlis.Framework.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\*.json" />
  </ItemGroup>
</Project>
