<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Majlis.Framework.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Majlis.Framework.Domain\Majlis.Framework.Domain.csproj" />
    <ProjectReference Include="..\Majlis.Framework.EntityFrameworkCore\Majlis.Framework.EntityFrameworkCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="OpenIddict.Validation.AspNetCore" />
    <PackageReference Include="OpenIddict.Validation.SystemNetHttp" />
    <PackageReference Include="Refit.HttpClientFactory" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\*.json" />
  </ItemGroup>
</Project>
