<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Majlis.Workspaces.EntityFrameworkCore</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Majlis.Workspaces.Domain\Majlis.Workspaces.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Majlis.Framework.EntityFrameworkCore\Majlis.Framework.EntityFrameworkCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
</Project>
